# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeverApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='user_id',
        ),
    ]
