# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeverApp', '0002_remove_news_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
