# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeverApp', '0007_auto_20170703_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='p_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
