# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeverApp', '0009_auto_20170703_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source_Category_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsFeverApp.Categories')),
                ('s_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsFeverApp.Publisher')),
            ],
        ),
    ]
