# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeverApp', '0010_source_category_mapping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Source_Category_Mapping',
            new_name='SourceCategoryMapping',
        ),
    ]
