# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeverApp', '0013_auto_20170703_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecategorymap',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='NewsFeverApp.Publisher'),
        ),
    ]
