# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 16:45
from __future__ import unicode_literals

import NewsFeverApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeverApp', '0015_auto_20170704_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to=NewsFeverApp.models.get_image_path)),
            ],
        ),
    ]
